### ISSUE TITLE
Add programming port

### ISSUE THREAD

**Issue by griswaldbrooks** [kestrel-labs/superspreader#6]
Should breakout
- 3v3
- GND
- DIO0
- TX
- RX

**Comment by tylerjw** [comment]
Add debugging with a programming port, maybe?

**Comment by griswaldbrooks** [comment]
Debugging like JTAG or SWD?
The port I've added is the serial port with reset and DIO0 (clock pin?) which allows it to be programmed and read serial output.

**Comment by tylerjw** [comment]
I was thinking JTAG if possible. The newer ones I'm ordering have jtag and programming over USB built in, idk about the current one.
